---
- hosts: my_hosts
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull maharshi369/latest_calculator:latest

    - name: Run Docker container
      shell: docker run -d -p 8081:8080 maharshi369/latest_calculator:latest
